SRCS= \
	main.c\
	cleaner.c\
	keyhooks.c\
	object_utils.c\
	init.c\
	input_parser.c\
	objectify.c\
	object_init.c\
	parser_utils.c\
	vision_init.c\
	utils.c\
	report.c\
	report_utils.c\
	object_cleaner.c\
	vision_cleaner.c\
	validate_core.c\
	validate_utils_color.c\
	validate_utils_common.c\
	validate_utils_float.c\
	validate_vision.c\
	validate_object.c\
	debug.c\
	transform.c\
	material.c\
	postparse_utils.c\
	handle_missing_objs.c\
	testing.c\
	shader.c\
	validate_utils_extra.c\
	validate_utils_extra2.c\
	object_init_misc.c\
	textures_utils.c\
	load_textures.c

TUPLES=\
	tuples.c\
	obj_utils.c\
	obj_utils_new.c\
	obj_utils_s.c\
	scaler.c\
	normalization.c\
	products.c
COLORS=\
	colors.c\
	colors_utils.c\
	colors_operations.c
MATRIX=\
	matrix.c\
	matrix_utils.c\
	transformation.c\
	matrix_operation.c\
	determinant.c\
	submatrix.c\
	matrix_inv.c\
	matrix_mult.c\
	rotation_matrix.c
RAYS=\
	intersections.c\
	rays.c\
	normal_vec.c\
	reflect_vec.c\
	computes.c\
	plane_intersect.c\
	rays_render_utils.c\
	shadow.c
INCLUDES=\
	colors.h\
	debug.h\
	minirt.h\
	object.h\
	rays.h\
	utils.h
