SRCS= \
	main.c\
	cleaner.c\
	keyhooks.c\
	object.c\
	init.c\
	input_parser.c\
	objectify.c\
	object_init.c\
	parser_utils.c\
	vision_init.c\
	utils.c\
	report.c\
	report_utils.c\
	object_cleaner.c\
	vision_cleaner.c\
	validate_core.c\
	validate_utils_color.c\
	validate_utils_common.c\
	validate_utils_float.c\
	validate_vision.c\
	validate_object.c
TUPLES=\
	tuples.c\
	obj_utils.c\
	obj_utils_extra.c\
	scaler.c\
	normalization.c\
	products.c
COLORS=\
	colors.c\
	colors_utils.c\
	colors_operations.c
MATRIX=\
	matrix.c\
	matrix_utils.c
RAYS=\
	intersections.c\
	rays.c